# Generated by Django 3.0.2 on 2020-02-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='mensagem',
        ),
    ]
