# Generated by Django 3.0.2 on 2020-02-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_contato_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
