# Generated by Django 3.0.2 on 2020-02-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_pessoa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='usuario',
        ),
    ]
